// Порождающие
import './patterns/singleton.js'
import './patterns/constructor.js'
import './patterns/builder.js'
// Структурные
// Поведенческие
import './patterns/observer.js'
import './patterns/chain.js'
import './patterns/iterator.js'
import './patterns/command.js'
import './patterns/template.js'